### ISSUE TITLE
Rule proposal for "cast"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/coding-standard#24]
I'd like to propose:
- `cast_spaces: ['single']` https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/930dc93a1b90eb991d13e2766a340aa6922d4a2c/doc/rules/cast_notation/cast_spaces.rst
- `lowercase_cast` https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/930dc93a1b90eb991d13e2766a340aa6922d4a2c/doc/rules/cast_notation/lowercase_cast.rst
- `no_short_bool_cast` https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/930dc93a1b90eb991d13e2766a340aa6922d4a2c/doc/rules/cast_notation/no_short_bool_cast.rst
- `short_scalar_cast` https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/930dc93a1b90eb991d13e2766a340aa6922d4a2c/doc/rules/cast_notation/short_scalar_cast.rst

**Comment by ChristophWurst** [comment]
:+1: from me

**Comment by kesselb** [comment]
> cast_spaces: ['single']

I usually omit the extra space because the cast and variable belongs together, however the diff output is much nicer and the cast easier to spot with a space between :+1: 

400 files changed in server.

> lowercase_cast

0 files changed in server :raised_hands: 

> no_short_bool_cast

2 files changed in server.

> short_scalar_cast

1 file changed in server.

Pull Request: https://github.com/nextcloud/coding-standard/pull/25

**Comment by nickvergessen** [comment]
> 400 files changed in server.

Is it much better if we opt for `cast_spaces: ['none']`

**Comment by kesselb** [comment]
180 for none

**Comment by nickvergessen** [comment]
I'm fine both ways
